### ISSUE TITLE
Vector

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#23]
Is it possible to store and use a variable length vector?

**Comment by learnforpractice** [comment]
Is this what you are looking for?

https://github.com/uuosio/ascdk/blob/f2907d862be8382ad4e1f6c15e272ff308813438/examples/codegeneration/codegeneration.ts#L10

**Comment by jafri** [comment]
@learnforpractice will that work if I want to store lets say:

```
interface Data {
   a: Asset;
   b: Asset
}

 public a3: Data[]=[]
 ```

**Comment by learnforpractice** [comment]
The following code works. Code generation doesn't support interfaces currently.
```
@packer
class Data {
    constructor(
        public a: Asset,
        public b: Asset
    ){}
}

public a3: Data[]=[]
```
