### ISSUE TITLE
Allow export of main class

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#29]
```
@contract(escrow)
export class EscrowContract extends HelperContract {
```

the above code fails

**Comment by jafri** [comment]
@learnforpractice could you kindly try this out with the `allow` example

I keep running into this issue

```
ERROR TS2304: Cannot find name 'any'.

 export function contract(_: any): any {
```

**Comment by learnforpractice** [comment]
`any` is an undefined type in assemblyscript.

**Comment by jafri** [comment]
Yes but it builds fine without `export` on the contract, there is some other issue here..

**Comment by jafri** [comment]
Figured out the issue, there was a printed `contract` erroneously
