### ISSUE TITLE
Files not included into target

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#30]
It seems that files don't automatically get included into target even if there is an import from that file

Current workaround is to add the following to get it to include
```
@packer
class empty extends Table { constructor() { super(); } }
```

**Comment by jafri** [comment]
@learnforpractice do you think you could have a look at this please

**Comment by learnforpractice** [comment]
Not sure what you mean. Can you create a minimal example so I can test it?

**Comment by learnforpractice** [comment]
I don't think it's a problem.

Transform will generate a file in the target folder only if the corresponding file has been modified.

See the source code below:

https://github.com/uuosio/ascdk/blob/9e3fc60faad6c2bdaa31c4f291186c7b7ca05d99/ts-packages/transform/src/ascoption.js#L100

**Comment by jafri** [comment]
I understand that but doing it like this:
1.  its not applying the pre-processing of Name.fromString to Name.fromU64 in the imported file
2. Makes it harder to debug inside `target` folder since you're missing the imported file, and the path to it doesnt resolve
<img width="861" alt="Screen Shot 2022-03-30 at 8 56 04 PM" src="https://user-images.githubusercontent.com/13677357/160967091-37a3c703-f410-4428-926f-539739d88c9f.png">

**Comment by learnforpractice** [comment]
Yeah, the generated files are only for developers to view what the final files look like.

It's not used by the compiler anymore.

**Comment by learnforpractice** [comment]
And Name.fromString need to be optimized at the compiler level, not at the prepress level.

The current solution is temporary.
