### ISSUE TITLE
Secondary index divergent behavior?

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#34]
It seems that in some cases, deleting from DBI64 will auto delete from IDXDB as well

Relevant lines;
https://github.com/uuosio/ascdk/blob/84a32cf0dd7566ed647c0f2e6737738f34386995/as-packages/chain/assembly/mi.ts#L60-L69

I think this should instead be:

```
 removeEx(primary: u64): void { 
     let it = this.find(primary); 
     check(it.isOk(), "primary value not found!"); 
     this.db.remove(it.i); 
     for (let i=0; i<this.idxdbs.length; i++) { 
         let ret = this.idxdbs[i].findPrimaryEx(primary);  
         if (ret.i.isOk()) {
                  this.idxdbs[i].remove(ret.i); 
         }
     } 
 } 
 ```

I believe this would closer match the eosio.cdt implementation of:

https://github.com/EOSIO/eosio.cdt/blob/798162d323680fa6d4691bcea7928729213c7172/libraries/eosiolib/contracts/eosio/multi_index.hpp#L1938-L1948

Could you kindly check @learnforpractice

**Comment by learnforpractice** [comment]
It's not an issue, that's how multi_index works.

**Comment by learnforpractice** [comment]
https://github.com/uuosio/ascdk/blob/84a32cf0dd7566ed647c0f2e6737738f34386995/as-packages/chain/assembly/mi.ts#L66

This line of code is needed. if the check fails, something went wrong.

**Comment by jafri** [comment]
@learnforpractice have a look at the eosio.cdt code

```c++
            if( i < 0 ) {
              typename index_type::secondary_key_type secondary;
              i = secondary_index_db_functions<typename index_type::secondary_key_type>::db_idx_find_primary( _code.value, _scope, index_type::name(), objitem.primary_key(),  secondary );
            }
            if( i >= 0 )
               secondary_index_db_functions<typename index_type::secondary_key_type>::db_idx_remove( i );
```

It doesn't do a check, rather it does the equivalent of if(ret.i.isOk)

**Comment by learnforpractice** [comment]
Yeah, sounds like the c++ multi_index will cache the secondary value. That's not a big difference.

**Comment by jafri** [comment]
If deleting from DBI64:
`this.db.remove(it.i)`)

 it will auto delete from IDXDB, then:
 
 `check(ret.i.isOk())` will fail
 
 The same behavior doesn't fail on eosio.cdt
 
 Should it not be changed in ascdk?

**Comment by jafri** [comment]
I have verified in my code that:

Before `this.db.remove(it.i)` ->  `ret.i.isOk() == true`
After `this.db.remove(it.i)` ->  `ret.i.isOk() == false`

**Comment by learnforpractice** [comment]
Did you mentioned the following code?
```
         if (ret.i.isOk()) {
                  this.idxdbs[i].remove(ret.i); 
         }
```
That's a secondary iterator. Different from the first iterator.

**Comment by jafri** [comment]
Yes 

```
         if (ret.i.isOk()) {
                  this.idxdbs[i].remove(ret.i); 
         }
```

This is the modification I am suggesting

**Comment by learnforpractice** [comment]
I don't think that's a good change.

`this.idxdbs[i].findPrimaryEx` should always return a valid iterator. If it doesn't, there is a bug in the code. Your suggestion will hide this kink of bug.

**Comment by jafri** [comment]
@learnforpractice it wont always return valid iterator

Here is nodeos code:
```
void apply_context::db_remove_i64( int iterator ) {
   const key_value_object& obj = keyval_cache.get( iterator );

   const auto& table_obj = keyval_cache.get_table( obj.t_id );
   EOS_ASSERT( table_obj.code == receiver, table_access_violation, "db access violation" );

//   require_write_lock( table_obj.scope );

   update_db_usage( obj.payer,  -(obj.value.size() + config::billable_size_v<key_value_object>) );

   db.modify( table_obj, [&]( auto& t ) {
      --t.count;
   });
   db.remove( obj );

   if (table_obj.count == 0) {
      remove_table(table_obj);
   }

   keyval_cache.remove( iterator );
}
```

Look at: 
   if (table_obj.count == 0) {
      remove_table(table_obj);
   }
   
In this case findPrimaryEx will return error in `ascdk` when it shouldnt

**Comment by jafri** [comment]
This is why `eosio.cdt` does `if( i >= 0 )` instead of `check(i >= 0)`

**Comment by jafri** [comment]
Current `testmi` test suite doesn't catch this bug because there are more than 1 rows before calling `.remove`

When it is the last row being removed, `nodeos` deletes the entire table, thus trying to fetch secondary index using an intrinsic like env.db_idx128_find_primary will return error

**Comment by learnforpractice** [comment]
Ok, I think you are right. There indeed need an `if` check. The first secondary table has the same table name as dbi64. Deleting the dbi64 table will result in deleting the first secondary table.

I think this is a bug in eosio source code. the first secondary index should start from 1, not 0.

**Comment by learnforpractice** [comment]
Can you add a test case to `testmi.ts` that can indicate this issue has been solved?

**Comment by learnforpractice** [comment]
> Current `testmi` test suite doesn't catch this bug because there are more than 1 rows before calling `.remove`
> 
> When it is the last row being removed, `nodeos` deletes the entire table, thus trying to fetch secondary index using an intrinsic like `env.db_idx128_find_primary` (used by `this.idxdbs[i].findPrimaryEx`) will return error

I can't replicate this issue with the following code.
```
        for(;;) {
            let it = mi.lowerBound(0);
            if (!it.isOk()) {
                break;
            }
            mi.remove(it);
        }
```
Though the first secondary index db and primary db share the same table, deleting all primary db values won't delete the table entirely since `table_obj->count` is not zero at this time.

**Comment by jafri** [comment]
Hmm you are right, I didn't realize that secondary indexes have their own store call that increments count and decrements count as well

**Comment by jafri** [comment]
If you want to see where I'm running into this issue:

Source: https://github.com/jafri/ascdk-minimal/blob/22d5e3a27ef331a06f6d5b0e2805295fbfdbd0ef/contracts/allow/allow.contract.ts

Test: https://github.com/jafri/ascdk-minimal/blob/9e7efa48f3b8270343cbe58f3ef5beabb9ed1d07/contracts/allow/allow.spec.ts#L111
