### ISSUE TITLE
Dangerous primary

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#52]
```
    get primary(): u64 {
        if (!this.isOk()) {
            return 0;
        }

        if (this._primary != UNKNOWN_PRIMARY_KEY) {
            return this._primary;
        }

        let value = this.value;
        this._primary = value!.getPrimaryValue();
        return this._primary;
    }
```

returning 0 as primary key is dangerous on !isOk()... that may be a valid existing primary key on another iterator

Primary key is always the same, so at no point should it return 0 like that

**Comment by learnforpractice** [comment]
I think the best practice is to check the iterator before using primary.

What's your recommendation? Should we throw an error if the iterator is invalid?

**Comment by learnforpractice** [comment]
Improved by f77bccb904df854991fcf9d348433140d68892f7
