### ISSUE TITLE
Contract decorator

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#53]
Why do we need to specify a name like

@contract("name")

wouldn't just this work?

@contract

**Comment by learnforpractice** [comment]
That's for naming ABI file but is not in use currently.

**Comment by jafri** [comment]
I think it would be good to remove, new devs could get confused by it since that name is not what really matters, the name that matters is what account you deploy to

**Comment by learnforpractice** [comment]
Sounds reasonable, removed by 8189fe06c9113116a3c978fdb2f636784abfdf0a
