### ISSUE TITLE
Optional example?

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#56]
Do we have an example with optional

**Comment by learnforpractice** [comment]
Yes.
https://github.com/uuosio/ascdk/blob/a0bf318836a401ed59011c4fc265e2323f85b6f3/ts-packages/tests/testcodegen.ts#L21

**Comment by learnforpractice** [comment]
`optional` implementation has been improved.

https://github.com/uuosio/ascdk/blob/1118aba71858053358b9b4dd3587fc6cc4426def/as-packages/chain/tests/testoptional.ts#L21

**Comment by jafri** [comment]
@learnforpractice couldn't we treat:

a1: Asset | null

as optional?

**Comment by learnforpractice** [comment]
I don't think that's a good idea. `Asset | null` can be used for other purposes which may cause confusion.
The current implementation is compatible with C++ Smart Contracts.
