### ISSUE TITLE
Failing ExtendedSymbol not found

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#59]
I have published the failing branch 83ef1f249d2117b5faec82282f77650d3d189f20

Running command `yarn build:allow2` in examples

It is currently failing with:

```
Build Starting ······
++++++writeFile: ../../allow2/target/allow2.contract.abi
Build progressing. Generating target files ······
ERROR TS2304: Cannot find name 'ExtendedSymbol'.

     token!: ExtendedSymbol;
             ~~~~~~~~~~~~~~
 in allow2/allow2.contract.ts(51,13)

ERROR TS2304: Cannot find name 'ExtendedSymbol'.

         token: ExtendedSymbol | null = null,
                ~~~~~~~~~~~~~~
 in allow2/allow2.contract.ts(56,16)

ERROR TS2304: Cannot find name 'ExtendedSymbol'.

             let obj = new ExtendedSymbol();
                           ~~~~~~~~~~~~~~
 in allow2/allow2.contract.ts(77,27)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/as-chain/serializer/Packer'.

             dec.unpack(obj);
                        ~~~
 in allow2/allow2.contract.ts(78,24)

ERROR TS2339: Property 'token' does not exist on type 'allow2/allow2.contract/settokenAction'.

             this.token = obj;
                  ~~~~~
 in allow2/allow2.contract.ts(79,18)

ERROR TS2339: Property 'token' does not exist on type 'allow2/allow2.contract/settokenAction'.

             mycontract.settoken(args.token,args.isAllowed,args.isBlocked)
                                      ~~~~~
 in allow2/allow2.contract.ts(157,38)

ERROR TS2339: Property 'token' does not exist on type 'allow2/allow2.contract/settokenAction'.

         size += this.token.getSize();
                      ~~~~~
 in allow2/allow2.contract.ts(88,22)

ERROR TS2339: Property 'token' does not exist on type 'allow2/allow2.contract/settokenAction'.

         enc.pack(this.token);
                       ~~~~~
 in allow2/allow2.contract.ts(67,23)

FAILURE 8 compile error(s)
Build Done. Targets generated. Target directory: allow2/target.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by learnforpractice** [comment]
`import { ExtendedSymbol } from 'as-chain'` Fix this issue.

See the generated file in `target/allow2.contract.ts`, it's missing `ExtendedSymbol`

I don't have a better solution for this kind of issue currently.

I think it will be better to avoid extending a Contract class with action in it.

**Comment by jafri** [comment]
@learnforpractice how about a list that we replace like

Replace `Name` with `_chain.Name`
Replace `ExtendedSymbol` with `_chain.ExtendedSymbol`

**Comment by jafri** [comment]
One of the core features of this library is how extensible it is, recommending to not extend a contract class kills one of its main features. Ability to extend contracts without having to import ghost elements like ExtendedSymbol is the parent contract is definitely needed

**Comment by learnforpractice** [comment]
> 

That's an ugly fix. Must find out a better solution. The key point is to find out all the missing symbols used by the generated 
code.

**Comment by learnforpractice** [comment]
```
Replace Name with _chain.Name
Replace ExtendedSymbol with _chain.ExtendedSymbol
```
That sounds like a better solution.

**Comment by learnforpractice** [comment]
Fixed by b6e5cbc3f185aa1084492018ef3bed1f9d8b91a8

**Comment by jafri** [comment]
Fixed, beauty

@learnforpractice do you think we could add a way to tell transformer to compile an imported library too?

For example if I publish the `allow` contract as an `npm` package, when I run ascdk on a contract importing `allow` like:

```
import { AllowContract } from 'allow'
```

the transformer won't pick up that AllowContract needs to be compiled too, any way to resolve without having to do like:

```
import { AllowContract } from './node_modules/allow'
```

**Comment by learnforpractice** [comment]
Yeah, that's a new problem. Need to dig into the transform source code again.

**Comment by jafri** [comment]
@learnforpractice hope this helps

allow library in package.json state
```
"main": "./assembly/index.ts"
```

so essentially, in `readFile` ascdk is looking for : 

`'../node_modules/allow/assembly/index.ts'`

However in sourceModifier.fileExtMap it has
`'~lib/allow/index.ts'`


Here was a ugly hacky fix I tried that worked:

```
        if (relativePath.indexOf('allow') !== -1) {
            if (!sourceModifier.fileExtMap.has(relativePath)) {
                const alternativePath = relativePath.replace(/.*node_modules/, '~lib').replace('/assembly', '')
                if (sourceModifier.fileExtMap.has(alternativePath)) {
                    relativePath = alternativePath
                }
            }
        }

        if (sourceModifier.fileExtMap.has(relativePath)) {
```

**Comment by learnforpractice** [comment]
Yeah, sounds like you know how to fix it.

**Comment by jafri** [comment]
I actually am not sure of the best way to fix it, is this hacky fix the right way?

**Comment by learnforpractice** [comment]
That's the right place to fix it but needs to be improved to make it handle common cases  I think.

**Comment by jafri** [comment]
This works well

```
        // Transform library imports
        if (relativePath.indexOf('/as-chain/') === -1 && !sourceModifier.fileExtMap.has(relativePath)) {
            const alternativePath = relativePath.replace(/.*node_modules/, '~lib').replace('/assembly', '')
            if (sourceModifier.fileExtMap.has(alternativePath)) {
                relativePath = alternativePath
            }
        }
```

**Comment by learnforpractice** [comment]
Excuse me, what are you talking about? This issue has been fix. Is there a new problems?

**Comment by jafri** [comment]
I think there is some issue with github @learnforpractice its re-sending old email replies

**Comment by learnforpractice** [comment]
Ok, got it.
