### ISSUE TITLE
Add .prefix() expression to {name}

### ISSUE THREAD

**Issue by DenisCarriere** [uuosio/ascdk#60]
Implemented in EOSIO CDT:
- https://github.com/EOSIO/eosio.cdt/issues/648
- https://github.com/EOSIO/eosio.cdt/pull/805/files

## Example 1

```java
name account = name{"my.account"};
name suffix = account.suffix(); // => "account"
name prefix = account.prefix(); // => "my"
```

## Example 2

For names with multiple prefixes, split name at the first `.` dot to the right.

```java
name account = name{"a.my.account"};
name suffix = account.suffix(); // => "account"
name prefix = account.prefix(); // => "a.my"

name subsuffix = prefix.suffix(); // => "my"
name subprefix = prefix.prefix(); // => "a"
```

**Comment by jafri** [comment]
Closed by 9597b8739bc388a63b03d083d928d528301be96b
