### ISSUE TITLE
Able to to include environment/config variables

### ISSUE THREAD

**Issue by DenisCarriere** [uuosio/ascdk#63]
Ability to include custom environment variables at compile time.

Use default `.env` file or `config/default.json`

- https://github.com/node-config/node-config
- https://github.com/motdotla/dotenv

Override env/config with specific file path

```
npx eosio-asc contract.ts --env .env
npx eosio-asc contract.ts --config ./config/default.json
```

Code example

```ts
import { print, Name } from "as-chain"

const config = process.env.get("CONFIG");

@contract
class MyContract {
    constructor(
        public receiver: Name,
        public firstReceiver: Name,
        public action: Name) {
    }

    @action("sayhello")
    sayHello():  void {
        print(`hello! ${config}`);
    }
}
```

**Comment by DenisCarriere** [comment]
using `process.env.get()` would receive the following error when deploying contract:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/550895/165850619-92378d84-896f-400e-a7be-4653e9be25d0.png">

**Comment by learnforpractice** [comment]
I recommend using the method in the following example in order to avoid increasing code size and reducing performance.

https://github.com/uuosio/ascdk/tree/master/examples/config

**Comment by DenisCarriere** [comment]
Thanks for the suggestion, that should do the trick for configuration
