### ISSUE TITLE
Allow destructuring chain imports

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#7]
Currently all chain import have to be specified in this way:

```
import * as chain from 'as-chain'

// use chain.Asset, etc
```

It would help readability if we could destructure items like

```
import { Name, Symbol, Asset, check } from 'as-chain'

// use check() or new Name()
```

Destructuring currently breaks the build process

**Comment by learnforpractice** [comment]
Can you show me the code that doesn't work?

https://github.com/uuosio/ascdk/blob/084e4ea08d5b4a1d548e99d97bc20968662ce982/as-packages/chain/tests/testtable.ts#L1

This code works well.

**Comment by jafri** [comment]
@learnforpractice try this https://github.com/jafri/ascdk/blob/ascdk-dev/examples/eosio.token/eosio.token.ts
