### ISSUE TITLE
Add support for writing unit tests in js&ts

### ISSUE THREAD

**Issue by learnforpractice** [uuosio/ascdk#74]

**Comment by jafri** [comment]
Have a look here: https://github.com/ProtonProtocol/vert

Have been doing this for a while, works well with ascdk

**Comment by learnforpractice** [comment]
Yeah, I'm thinking about a more compatible approach.

**Comment by jafri** [comment]
How python runs tests using chain tester is really compatible, maybe similar for JS/TS?

**Comment by jafri** [comment]
Also I realized theres no real way to test the new intrinsics since ascdk doesn't use the new EOS repo: https://github.com/eosnetworkfoundation/mandel

**Comment by learnforpractice** [comment]
> Also I realized theres no real way to test the new intrinsics since ascdk doesn't use the new EOS repo: https://github.com/eosnetworkfoundation/mandel

Under planning.

**Comment by jafri** [comment]
An interesting idea I had here was, what if we modified `ascdk` to be `portable`. The AS compiler itself is written in portable Assemblyscript. What this allows for is compiling using `tsc`, then tests could theoretically be run against a JS compiled version of the contract, and get full JS support + debugger

**Comment by learnforpractice** [comment]
Sounds practical. some low-level functions such as `store`, and 'load` wouldn't work though.

**Comment by jafri** [comment]
we could replace them with custom imports

**Comment by learnforpractice** [comment]
That make things much more complicated. I think we should recommend developers not to use low-level functions.

**Comment by jafri** [comment]
Thats fine for devs but I believe `ascdk` library itself uses store and load

**Comment by learnforpractice** [comment]
So we need to replace all these functions in the assemblyscript source code which is not compatible with the typescript with custom functions. That's a practical solution.

**Comment by jafri** [comment]
Is it possible to use a debugger/breakpoints?

**Comment by learnforpractice** [comment]
It is possible to debug wasm in a browser.  See the following link:

https://blog.bitsrc.io/debugging-webassembly-with-chrome-devtools-99dbad485451

For debugging smart contracts in wasm, there is no good solution I think.

The solution I currently use for debugging Rust & Go Smart Contracts is compiling source code to native which is not possible for Assemblyscript Smart Contracts I think.
