### ISSUE TITLE
Output WASM and ABI to same folder, with same name

### ISSUE THREAD

**Issue by jafri** [uuosio/ascdk#8]
Will make uploading to chain easier

`npx eosio-asc examples/eosio.token/eosio.token.ts`

should generate

```
examples/eosio.token/eosio.token.wasm
examples/eosio.token/eosio.token.abi
examples/eosio.token/eosio.token.wast
```

**Comment by learnforpractice** [comment]
Command with `npx eosio-asc assembly/hello.ts -b build/hello.wasm -t build/hello.wat` suppose to fix this issue.

But this command does not generate the wasm file properly.
